version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PatientRecordManagementSystem"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
s3_prefix = "PatientRecordManagementSystem"
parameter_overrides = "CognitoUserPoolClientId=\"Naimefeteni_24\" CognitoDomain=\"project-capstone-remote-cicd\" S3Bucket=\"capstone-cicd-remote-yosief.abraham\" FrontendDeployment=\"remote\""
disable_rollback = true
