version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::751018890790:user/aws-sam-cli-managed-CapsStone-Remote-p-PipelineUser-lLCRrdnNv2Bh"
permissions_provider = "AWS IAM"

[CapsStone-Remote.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::751018890790:role/aws-sam-cli-managed-CapsStone-PipelineExecutionRole-FfE4SpYdxSUf"
cloudformation_execution_role = "arn:aws:iam::751018890790:role/aws-sam-cli-managed-CapsS-CloudFormationExecutionRo-VZtMOAuh3hzn"
artifacts_bucket = "aws-sam-cli-managed-capsstone-remo-artifactsbucket-7ijcrikrmpxe"
image_repository = ""
region = "us-east-2"

[CapStone_Remote.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::751018890790:role/aws-sam-cli-managed-CapStone--PipelineExecutionRole-WH4M11ytQe0B"
cloudformation_execution_role = "arn:aws:iam::751018890790:role/aws-sam-cli-managed-CapSt-CloudFormationExecutionRo-7YHF0bp1pwkv"
artifacts_bucket = "aws-sam-cli-managed-capstone-remot-artifactsbucket-rj2agr5uki2d"
image_repository = ""
region = "us-east-2"

[CapStone-Remote.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::751018890790:role/aws-sam-cli-managed-CapStone--PipelineExecutionRole-JXFXX9E9AY0z"
cloudformation_execution_role = "arn:aws:iam::751018890790:role/aws-sam-cli-managed-CapSt-CloudFormationExecutionRo-IPZFinIT4Nmo"
artifacts_bucket = "aws-sam-cli-managed-capstone-remot-artifactsbucket-z32cfpsydjdf"
image_repository = ""
region = "us-east-2"

[Naihiji.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::751018890790:role/aws-sam-cli-managed-Naihiji-p-PipelineExecutionRole-DVzXhHBARrVw"
cloudformation_execution_role = "arn:aws:iam::751018890790:role/aws-sam-cli-managed-Naihi-CloudFormationExecutionRo-2AxRN1fwrLmc"
artifacts_bucket = "aws-sam-cli-managed-naihiji-pipeli-artifactsbucket-7wvuepykya9f"
image_repository = ""
region = "us-east-2"
